#!/bin/bash

# This File Define Colors for all Shell Scripts
black="\033[0;30m"        # Black
red="\033[0;91m"          # Red
green="\033[0;92m"        # Green
yellow="\033[0;93m"       # Yellow
blue="\033[0;94m"         # Blue
purple="\033[0;95m"       # Purple
cyan="\033[0;36m"         # Cyan
white="\033[0;97m"        # White

# Blinking 
blblack="\033[5;30m"        # Black
blred="\033[5;91m"          # Red
blgreen="\033[5;32m"        # Green
blyellow="\033[5;93m"       # Yellow
blblue="\033[5;34m"         # Blue
blpurple="\033[5;95m"       # Purple
blcyan="\033[5;36m"         # Cyan
blwhite="\033[5;97m"        # White

# Bold
BBlack="\033[1;30m"       # Black
BRed="\033[1;31m"         # Red
BGreen="\033[1;32m"       # Green
BYellow="\033[1;33m"      # Yellow
BBlue="\033[1;34m"        # Blue
BPurple="\033[1;35m"      # Purple
BCyan="\033[1;36m"        # Cyan
BWhite="\033[1;37m"       # White

# Underline
UBlack="\033[4;30m"       # Black
URed="\033[4;31m"         # Red
UGreen="\033[4;32m"       # Green
UYellow="\033[4;33m"      # Yellow
UBlue="\033[4;34m"        # Blue
UPurple="\033[4;35m"      # Purple
UCyan="\033[4;36m"        # Cyan
UWhite="\033[4;37m"       # White

# Various variables you might want for your PS1 prompt instead
Time12h="\T"
Time12a="\@"
PathShort="\w"
PathFull="\W"
NewLine="\n"
Jobs="\j"

cout(){
  printf "$white[$BBlue+$white] %s\n" "$*"
}
cerr(){
  printf "$white[$BRed-$white] %s\n" "$*"
}
notify(){
  printf "$white[$BGreen*$white] %s\n" "$*"
}
warn(){
  printf "$white[$BRed!$white] %s\n" "$*"
}
inform(){
  printf "$white[${BYellow}i$white] %s\n" "$*"
}

unknown(){
  printf "$white[${BPurple}?$white] %s\n" "$*"
}
